### ISSUE TITLE
[npm]: Publish latest version of @napi-rs/ttf2woff2 on npm

### ISSUE THREAD

**Issue by KonghaYao** [Brooooooklyn/woff-build#33]
<img width="652" alt="image" src="https://github.com/Brooooooklyn/woff-build/assets/68177907/cd0952ec-4a09-4d9f-bbc3-e52692533d3c">

I see that the project has been released with version 0.1.1, but it hasn't been published to npm yet.

**Comment by yisibl** [comment]
We have changed the name, please use the new `@napi-rs/woff-build`.

https://www.npmjs.com/package/@napi-rs/woff-build
